name: CI

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "kolokush"
          git config user.email "david.kush98767@gmail.com"

      - name: Run a one-line script
        run: |
          echo " " >> README.md
          git add README.md
          git commit -m "Always green!"

      - name: Push changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git remote set-url origin https://kolokush:${{ secrets.ACTIONS_PAT }}@github.com/KoloKush/DeskPal
          git push origin HEAD:main
